name: Run tests
on: [pull_request]
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: '3.5'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install tests requirements
        run: pip install -r test-requirements.txt
      - name: Run tests
        run: python3 -m pytest -v tests
